name: Build Executables

on: workflow_dispatch

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'macos-13', 'macos-latest']  # macos-13 is intel, macos-latest is arm

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'

    - name: Install panoptes aggregation
      run: |
        pip install -U pip
        pip install .[gui,installer]
      working-directory: ./

    - name: Build executable (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        pyinstaller --clean build_win.spec
      working-directory: ./

    - name: Build executable (macOS)
      if: matrix.os != 'windows-latest'
      run: |
        pyinstaller --clean build_mac.spec
      working-directory: ./

    - name: Collect licenses
      run: |
        pip-licenses --format=plain-vertical --with-authors --with-urls --with-license-file --no-license-path --output-file=dist/dependency_licenses_full.txt
        pip-licenses --format=markdown --with-authors --with-urls --output-file=dist/dependency_licenses_summary.txt

    - name: Create Artifact (Windows x64)
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: windows-x64-executables
        path: dist/

    - name: Create Artifact (macOS arm)
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v4
      with:
        name: macos-arm64-executables
        path: |
          dist/*.app
          dist/*.txt

    - name: Create Artifact (macOS intel)
      if: matrix.os == 'macos-13'
      uses: actions/upload-artifact@v4
      with:
        name: macos-intel-executables
        path: |
          dist/*.app
          dist/*.txt
